// <auto-generated />
using System;
using CoachingAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoachingAPI.Migrations
{
    [DbContext(typeof(PlayersDbContext))]
    partial class PlayersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CoachingAPI.Models.Map", b =>
                {
                    b.Property<int>("Name")
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.HasKey("Name");

                    b.ToTable("Map", (string)null);
                });

            modelBuilder.Entity("CoachingAPI.Models.Match", b =>
                {
                    b.Property<Guid>("MatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("MatchPlatform")
                        .HasColumnType("int");

                    b.Property<string>("WinnerTeamName")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MatchId");

                    b.HasIndex("WinnerTeamName");

                    b.ToTable("Match", (string)null);
                });

            modelBuilder.Entity("CoachingAPI.Models.Membership", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TeamName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LeaveDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MembershipType")
                        .HasColumnType("int");

                    b.HasKey("PlayerId", "TeamName");

                    b.HasIndex("TeamName");

                    b.ToTable("Membership", (string)null);
                });

            modelBuilder.Entity("CoachingAPI.Models.Player", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCoach")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlayerId");

                    b.ToTable("Player", (string)null);
                });

            modelBuilder.Entity("CoachingAPI.Models.PlayerMapStats", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MapName")
                        .HasColumnType("int");

                    b.Property<int>("CtPistolRoundsLost")
                        .HasColumnType("int");

                    b.Property<int>("CtPistolRoundsPlayed")
                        .HasColumnType("int");

                    b.Property<int>("CtPistolRoundsWon")
                        .HasColumnType("int");

                    b.Property<int>("CtRoundsPlayed")
                        .HasColumnType("int");

                    b.Property<int>("Losses")
                        .HasColumnType("int");

                    b.Property<int>("MatchesPlayed")
                        .HasColumnType("int");

                    b.Property<int>("TPistolRoundsLost")
                        .HasColumnType("int");

                    b.Property<int>("TPistolRoundsPlayed")
                        .HasColumnType("int");

                    b.Property<int>("TPistolRoundsWins")
                        .HasColumnType("int");

                    b.Property<int>("TRoundsPlayed")
                        .HasColumnType("int");

                    b.Property<int>("TotalRoundsPlayed")
                        .HasColumnType("int");

                    b.Property<int>("Wins")
                        .HasColumnType("int");

                    b.HasKey("PlayerId", "MapName");

                    b.HasIndex("MapName");

                    b.ToTable("PlayerMapStatistics", (string)null);
                });

            modelBuilder.Entity("CoachingAPI.Models.PlayerStats", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Assists")
                        .HasColumnType("int");

                    b.Property<int>("Deaths")
                        .HasColumnType("int");

                    b.Property<int>("Headshots")
                        .HasColumnType("int");

                    b.Property<int>("KDRatio")
                        .HasColumnType("int");

                    b.Property<int>("KRRatio")
                        .HasColumnType("int");

                    b.Property<int>("Kills")
                        .HasColumnType("int");

                    b.Property<int>("Losses")
                        .HasColumnType("int");

                    b.Property<int>("Wins")
                        .HasColumnType("int");

                    b.HasKey("PlayerId");

                    b.ToTable("PlayerStatistics", (string)null);
                });

            modelBuilder.Entity("CoachingAPI.Models.Team", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsMatchMaking")
                        .HasColumnType("bit");

                    b.HasKey("Name");

                    b.ToTable("Team", (string)null);
                });

            modelBuilder.Entity("MatchTeam", b =>
                {
                    b.Property<Guid>("MatchesMatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TeamsName")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MatchesMatchId", "TeamsName");

                    b.HasIndex("TeamsName");

                    b.ToTable("MatchTeam", (string)null);
                });

            modelBuilder.Entity("CoachingAPI.Models.Match", b =>
                {
                    b.HasOne("CoachingAPI.Models.Team", "Winner")
                        .WithMany("WonMatches")
                        .HasForeignKey("WinnerTeamName");

                    b.Navigation("Winner");
                });

            modelBuilder.Entity("CoachingAPI.Models.Membership", b =>
                {
                    b.HasOne("CoachingAPI.Models.Player", "Player")
                        .WithMany("Memberships")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoachingAPI.Models.Team", "Team")
                        .WithMany("Memberships")
                        .HasForeignKey("TeamName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("CoachingAPI.Models.PlayerMapStats", b =>
                {
                    b.HasOne("CoachingAPI.Models.Map", "Map")
                        .WithMany()
                        .HasForeignKey("MapName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoachingAPI.Models.PlayerStats", "Player")
                        .WithMany("MapStats")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Map");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("CoachingAPI.Models.PlayerStats", b =>
                {
                    b.HasOne("CoachingAPI.Models.Player", "Player")
                        .WithOne("Stats")
                        .HasForeignKey("CoachingAPI.Models.PlayerStats", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("MatchTeam", b =>
                {
                    b.HasOne("CoachingAPI.Models.Match", null)
                        .WithMany()
                        .HasForeignKey("MatchesMatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoachingAPI.Models.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamsName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CoachingAPI.Models.Player", b =>
                {
                    b.Navigation("Memberships");

                    b.Navigation("Stats")
                        .IsRequired();
                });

            modelBuilder.Entity("CoachingAPI.Models.PlayerStats", b =>
                {
                    b.Navigation("MapStats");
                });

            modelBuilder.Entity("CoachingAPI.Models.Team", b =>
                {
                    b.Navigation("Memberships");

                    b.Navigation("WonMatches");
                });
#pragma warning restore 612, 618
        }
    }
}
