// <auto-generated />
using System;
using BlazerServerCoaching.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazerServerCoaching.Migrations
{
    [DbContext(typeof(MatchDbContex))]
    [Migration("20240215113653_test20")]
    partial class test20
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazerServerCoaching.Data.Models.Match", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<bool?>("CTPistol")
                        .HasColumnType("bit");

                    b.Property<int?>("CTSideL")
                        .HasColumnType("int");

                    b.Property<int?>("CTSideW")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Maps")
                        .HasColumnType("int");

                    b.Property<string>("Oppenent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<bool?>("TPistol")
                        .HasColumnType("bit");

                    b.Property<int?>("TSideL")
                        .HasColumnType("int");

                    b.Property<int?>("TSideW")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Matchs");
                });

            modelBuilder.Entity("BlazerServerCoaching.Data.Models.Team", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<int?>("CoachId")
                        .HasColumnType("int");

                    b.Property<int?>("Player_1Id")
                        .HasColumnType("int");

                    b.Property<int?>("Player_2Id")
                        .HasColumnType("int");

                    b.Property<int?>("Player_3Id")
                        .HasColumnType("int");

                    b.Property<int?>("Player_4Id")
                        .HasColumnType("int");

                    b.Property<int?>("Player_5Id")
                        .HasColumnType("int");

                    b.Property<string>("TeamDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CoachId");

                    b.HasIndex("Player_1Id");

                    b.HasIndex("Player_2Id");

                    b.HasIndex("Player_3Id");

                    b.HasIndex("Player_4Id");

                    b.HasIndex("Player_5Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("BlazerServerCoaching.Data.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BlazerServerCoaching.Data.Models.Team", b =>
                {
                    b.HasOne("BlazerServerCoaching.Data.Models.User", "Coach")
                        .WithMany()
                        .HasForeignKey("CoachId");

                    b.HasOne("BlazerServerCoaching.Data.Models.User", "Player_1")
                        .WithMany()
                        .HasForeignKey("Player_1Id");

                    b.HasOne("BlazerServerCoaching.Data.Models.User", "Player_2")
                        .WithMany()
                        .HasForeignKey("Player_2Id");

                    b.HasOne("BlazerServerCoaching.Data.Models.User", "Player_3")
                        .WithMany()
                        .HasForeignKey("Player_3Id");

                    b.HasOne("BlazerServerCoaching.Data.Models.User", "Player_4")
                        .WithMany()
                        .HasForeignKey("Player_4Id");

                    b.HasOne("BlazerServerCoaching.Data.Models.User", "Player_5")
                        .WithMany()
                        .HasForeignKey("Player_5Id");

                    b.Navigation("Coach");

                    b.Navigation("Player_1");

                    b.Navigation("Player_2");

                    b.Navigation("Player_3");

                    b.Navigation("Player_4");

                    b.Navigation("Player_5");
                });
#pragma warning restore 612, 618
        }
    }
}
